version: '3'

services:

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - appv:/usr/src/app
      - staticv:/usr/src/app/static
      - mediav:/usr/src/app/media

    networks:
      - redis_network
      - pg_network
      - nginx_network
    env_file: .env
    environment:
      DEBUG: 'false'
    command: /usr/local/bin/gunicorn trades.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"            # host:local ports: use port 8080
    volumes:
      - staticv:/usr/src/app/static    # /www/static
      - mediav:/usr/src/app/media
    # volumes_from:
    #  - web
    links:
      - web:web
    networks:
      - nginx_network

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - pg_network

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - redis_network

networks:
  pg_network:
    driver: bridge
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  appv:
  staticv:
  mediav:
  redisdata:
  pgdata:
